%% Script for fitting the interblade distribution histogram with a Gaussian mixture model with six peaks
    % version 1.1 (25/07/2025)
    % written by Clement Verkest & Stefan G Lechner
    % INPUT: requires the 'result' structure generated by 'MFX_PIEZO1_ALFA_01_main_script.m'


% function FitInterbladeDistribution(result, DataSource)

%load data
data = result.InterBlades(:,4);
% data = myinter;
DataSource = 1;

% Define individual Gaussian function
gaussian = @(amp, mean, sigma, y) amp * exp(-((y - mean).^2) / (2 * sigma^2));

% set limits 
 MaxSigma =[2 2 1 3 1 1]; 
if DataSource == 6
    MaxSigma =[2 2 2 1 2 2];
end

if DataSource == 5
    MaxSigma =[2 1 0.25 2 1.5 1];
end

if DataSource == 1
    MaxSigma =[2 2 2 1 3 2];
end

if DataSource == 0
 MaxSigma =[2 2 1 3 1 1]; 
end

% Define histogram edges
bin_edges = 5:1:40;
bin_centers = bin_edges(1:end-1) + diff(bin_edges)/2;

% Estimate histogram density
[counts, ~] = histcounts(data, bin_edges);
normalized_counts = counts / trapz(bin_centers, counts); % Normalize to make it a probability density

% Initial guesses for means, amplitudes, and standard deviations
    initial_params = [max(normalized_counts), 10, 1, max(normalized_counts), 18, 1, max(normalized_counts), 19.5, 1, max(normalized_counts), 22.5, 1, max(normalized_counts), 27, 1, max(normalized_counts), 32, 1];

if DataSource == 1
    initial_params = [max(normalized_counts), 12, 1, max(normalized_counts), 17, 1, max(normalized_counts), 21.5, 1, max(normalized_counts), 25.5, 1, max(normalized_counts), 28, 1, max(normalized_counts), 32, 1];
end

if DataSource == 0
    initial_params = [max(normalized_counts), 10, 1, max(normalized_counts), 18, 1, max(normalized_counts), 19.5, 1, max(normalized_counts), 22.5, 1, max(normalized_counts), 27, 1, max(normalized_counts), 32, 1];
end

% Define bounds
lower_bounds = [0, 0, 0.1, 0, 0, 0.1, 0, 0, 0.1, 0, 0, 0.1, 0, 0, 0.1, 0, 0, 0.1];
upper_bounds = [Inf, 40, MaxSigma(1), Inf, 40, MaxSigma(2), Inf, 40, MaxSigma(3), Inf, 40, MaxSigma(4), Inf, 40, MaxSigma(5), Inf, 40, MaxSigma(6)];

% Define Gaussian sum function with variable means and sigmas
gaussianSum = @(params, y) gaussian(params(1), params(2), params(3), y) + ...
                             gaussian(params(4), params(5), params(6), y) + ...
                             gaussian(params(7), params(8), params(9), y) + ...
                             gaussian(params(10), params(11), params(12), y) + ...
                             gaussian(params(13), params(14), params(15), y) + ...
                             gaussian(params(16), params(17), params(18), y);


% Fit the function using lsqcurvefit with max iterations
opts = optimset('Display', 'off', 'MaxIter', 500); % Suppress output and set max iterations
gaus_params_fit = lsqcurvefit(@(p, x) gaussianSum(p, x), initial_params, bin_centers, normalized_counts, lower_bounds, upper_bounds, opts);

% Extract fitted parameters
fitted_amplitudes = [gaus_params_fit(1), gaus_params_fit(4), gaus_params_fit(7), gaus_params_fit(10), gaus_params_fit(13), gaus_params_fit(16)];
fitted_means = [gaus_params_fit(2), gaus_params_fit(5), gaus_params_fit(8), gaus_params_fit(11), gaus_params_fit(14), gaus_params_fit(17)];
fitted_sigmas = [gaus_params_fit(3), gaus_params_fit(6), gaus_params_fit(9), gaus_params_fit(12), gaus_params_fit(15), gaus_params_fit(18)];

% Calculate proportions of each Gaussian component
total_area = sum(fitted_amplitudes .* fitted_sigmas * sqrt(2 * pi));
proportions = (fitted_amplitudes .* fitted_sigmas * sqrt(2 * pi)) / total_area;

% Display proportions
disp('Proportion of each Gaussian component:');
disp(proportions);

% Display means
disp('Mean of each Gaussian component:');
disp(fitted_means);

% Calculate and display goodness of fit (R-squared)
predicted_counts = gaussianSum(gaus_params_fit, bin_centers);
SS_res = sum((normalized_counts - predicted_counts).^2);
SS_tot = sum((normalized_counts - mean(normalized_counts)).^2);
R_squared = 1 - (SS_res / SS_tot);

disp('Goodness of fit (R-squared):');
disp(R_squared);

% Plot histogram and fitted curve
screenSize = get(0, 'ScreenSize');
figure('Position',[0 (screenSize(4)/2) 500 200]);;
bar(bin_centers, normalized_counts, 'FaceColor', [0.6 0.6 0.6],'FaceAlpha', 0.5, 'EdgeColor', 'k', 'DisplayName', 'Histogram'); hold on;
ax = gca;
ax.TickDir = 'out';
ax.Box = 'off';
ax.YLim = [0 0.15];

if DataSource == 1 || DataSource == 5 || DataSource == 6 || DataSource == 0
    % Generate smooth x values for plotting
    smooth_x = linspace(min(bin_centers), max(bin_centers), 1000);
    smooth_y = gaussianSum(gaus_params_fit, smooth_x);
    plot(smooth_x, smooth_y, 'k', 'LineWidth', 1, 'DisplayName', 'Fitted Gaussians');

    % Plot individual Gaussians
    for i = 1:6
        plot(smooth_x, gaussian(fitted_amplitudes(i), fitted_means(i), fitted_sigmas(i), smooth_x), 'Color', [0.8 0 1], 'LineWidth', 1.5, 'DisplayName', ['Gaussian ' num2str(i)]);
    end
end

% legend;
xlabel('interblade distance (nm)'); ylabel('probability');

% clean up
clearvars -except myinter IndivTrimersRAW IndivTrimersRAW_avg MFXdata MFX_data_files result traces_AVG traces_AVG_noMerge traces_FILT traces_RAW

% end
